// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDMBHT6x_FBDS1xOJ9CZepd45GS7Fg6r4',
    appId: '1:286725574913:android:7cee8ea1622fb832d7cb00',
    messagingSenderId: '286725574913',
    projectId: 'e-shop-b41d0',
    databaseURL: 'https://e-shop-b41d0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'e-shop-b41d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI2scvAUasdOLJuGEEoqpzLH6Gld0mtCY',
    appId: '1:286725574913:ios:f088a0821f9dca06d7cb00',
    messagingSenderId: '286725574913',
    projectId: 'e-shop-b41d0',
    databaseURL: 'https://e-shop-b41d0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'e-shop-b41d0.appspot.com',
    androidClientId: '286725574913-dh9u6tnjgn053c708isscoakgmisovg9.apps.googleusercontent.com',
    iosClientId: '286725574913-mmjt4ckra0tdtf2hlujnp27s2s8djll0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eShop',
  );
}
